language: node_js

node_js:
  - 6.10.2

services:
  - postgresql

before_script:
  - psql -c 'drop database if exists okdocs_test;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - NODE_ENV=test npm run migrate

script: 
  - npm test
# after_success:
#   - "cat ./coverage/lcov.info | coveralls"
